version: "3.8"

services:
  api:
    build: .
    image: eeg-api:latest
    ports:
      - "8000:8000"

    # --- PERBAIKANNYA DI SINI ---

    # 1. Atur working directory ke /app/src
    #    (Dockerfile kita menempatkan folder 'src' di /app/src)
    working_dir: /app/src

    # 2. Sekarang jalankan 'python api.py' DARI DALAM /app/src
    #    Ini akan memperbaiki semua masalah relative path.
    command: ["python", "api.py"]
