# Nama workflow, akan muncul di tab "Actions" GitHub
name: CI/CD - Build and Push Docker Image

# Pemicu (trigger) workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# --- BARU: Definisikan Environment Variable ---
env:
  # Kita buat nama image lengkap.
  # 'github.repository' adalah 'assidik12/eeg-motor-imagery-bci'
  # 'github.sha' adalah ID unik (hash) dari commit Anda
  IMAGE_NAME: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  # Kita ganti nama jobnya
  build-and-push:
    runs-on: ubuntu-latest

    # --- BARU: Izin untuk Push ke GHCR ---
    permissions:
      contents: read
      packages: write # Izin untuk menulis ke 'packages' (GHCR)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- BARU: Login ke GitHub Container Registry ---
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Username Anda (otomatis)
          password: ${{ secrets.CR_PAT }} # "Kunci" yang Anda buat di Tindakan 2

      - name: Create dummy model file for CI build
        run: |
          mkdir -p models
          echo "This is a dummy file for CI" > models/eegnet_model.h5

      # --- DIPERBARUI: Build dan Push ---
      - name: Build and Push Docker image
        # Kita set DOCKER_IMAGE_TAG agar docker-compose menggunakannya
        # Kita gunakan 'docker compose push' untuk mendorong image
        run: |
          export DOCKER_IMAGE_TAG=${{ github.sha }}
          docker compose build
          docker compose push
